name: Build and test

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Configure
        uses: actions/setup-node@v4
        with:
          node-version: 16
          cache: npm
      - name: Install
        run: npm ci
      - name: Check format
        run: npm run prettier:check
      - name: Run tests
        run: npm run test
      - name: Build
        run: npm run build
